export type Lang = "es" | "en";

const translations = {
  es: {
    siteName: "SismoVenezuela",
    tagline: "Daños en tiempo real",
    report: "+ Reportar",
    sources: "🔗 Fuentes",
    news: "📰 Noticias",
    helpBtn: "¿Cómo usar?",
    langToggle: "EN",
    bannerUsgs: "⚠️ USGS",
    confirmed: "confirmados",
    estimated: "10K–100K est. USGS",
    deaths: "muertos",
    injured: "heridos",
    missing: "desaparecidos",
    tabs: {
      reports: "Reportes",
      personas: "Personas",
      edificios: "Edificios",
      solicitudes: "Solicitudes",
      acopios: "Centros de Acopio",
    },
    news_modal: {
      title: "Últimas noticias analizadas",
      subtitle: "Generado por Gemma 4 · Fuentes públicas",
      key_events: "Eventos clave",
      infrastructure: "Infraestructura",
      gov_response: "Respuesta gubernamental",
      sources: "Fuentes",
      no_digest: "Sin resumen disponible — ejecuta scrapers/news_digest.py",
      stale: "Resumen desactualizado",
    },
    stats_modal: {
      title: "Estadísticas",
      buildings: "Edificios afectados",
      centers: "Centros de acopio activos",
      reports: "Reportes ciudadanos",
      historical: "Comparativa histórica",
    },
  },
  en: {
    siteName: "SismoVenezuela",
    tagline: "Real-time damage map",
    report: "+ Report",
    sources: "🔗 Sources",
    news: "📰 News",
    helpBtn: "How to use?",
    langToggle: "ES",
    bannerUsgs: "⚠️ USGS",
    confirmed: "confirmed",
    estimated: "10K–100K est. USGS",
    deaths: "deaths",
    injured: "injured",
    missing: "missing",
    tabs: {
      reports: "Reports",
      personas: "Missing",
      edificios: "Buildings",
      solicitudes: "Requests",
      acopios: "Relief Centers",
    },
    news_modal: {
      title: "Latest news analysis",
      subtitle: "Generated by Gemma 4 · Public sources",
      key_events: "Key developments",
      infrastructure: "Infrastructure",
      gov_response: "Government response",
      sources: "Sources",
      no_digest: "No digest available — run scrapers/news_digest.py",
      stale: "Digest may be outdated",
    },
    stats_modal: {
      title: "Statistics",
      buildings: "Affected buildings",
      centers: "Active relief centers",
      reports: "Community reports",
      historical: "Historical comparison",
    },
  },
} as const;

export function t(lang: Lang, key: string): string {
  const keys = key.split(".");
  let node: unknown = translations[lang];
  for (const k of keys) {
    if (typeof node !== "object" || node === null) return key;
    node = (node as Record<string, unknown>)[k];
  }
  return typeof node === "string" ? node : key;
}

export function useTranslations(lang: Lang) {
  return (key: string) => t(lang, key);
}
